### ISSUE TITLE
problem creating baseline

### ISSUE THREAD

**Issue by KinGsNowGH** [momibun926/redmine_issue_evm#191]
Everything works fine, but when i try to create a baseline i get this error:

```
Started GET "/projects/project-raizen-monit-radios/evmbaselines/new?id=61" for 127.0.0.1 at 2020-11-18 18:02:13 -0300
Processing by EvmbaselinesController#new as HTML
  Parameters: {"id"=>"61", "project_id"=>"project-raizen-monit-radios"}
  Current user: raphael.franca (id=6)
  Rendered plugins/redmine_issue_evm/app/views/evmbaselines/new.html.erb within layouts/base (18.8ms)
Completed 500 Internal Server Error in 65ms (ActiveRecord: 15.5ms)

ActionView::Template::Error (undefined method `gsub!' for :based_on:Symbol):
     9:     </p>
    10:     <p>
    11:       <%= f.label :based_on, l(:label_based_on) %>
    12:       <%= f.date_field :based_on, size: 8, required: true %><%= calendar_for(:based_on) %>
    13:     </p>
    14:     <p>
    15:       <%= label :bac, l(:label_baseline_bac) %>
  plugins/redmine_dmsf/lib/redmine_dmsf/patches/application_helper_patch.rb:40:in `calendar_for_with_square_brackets'
  plugins/redmine_issue_evm/app/views/evmbaselines/new.html.erb:12:in `block in _e626c62953ab2d7cfaa4c309035d8ae0'
  plugins/redmine_issue_evm/app/views/evmbaselines/new.html.erb:4:in `_e626c62953ab2d7cfaa4c309035d8ae0'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```
redmine_issue_evm              4.0.3

Environment:
  Redmine version                3.4.13.stable
  Ruby version                   2.3.8-p459 (2018-10-18) [x86_64-linux-gnu]
  Rails version                  4.2.11.1
  Environment                    production
  Database adapter               Mysql2
  Database timezone              -03
  ActiveRecord timezone          local
  App timezone                   UTC

**Comment by momibun926** [comment]
@KinGsNowGH 
Thank you for reporting.
Perhaps your installation of "redmine_dmsf" is the cause of the error. Its extended functionality does not seem to recognize "basis date of baseline" as a date.
If possible, could you please try to change it as follows?

`calendar_for(:based_on) -> calendar_for(@evm_baselines.based_on)'

at follow files,
app/views/evmbaselines/edit.html.erb
app/views/evmbaselines/new.html.erb
app/views/evmbaselines/show.html.erb
app/views/common/_option_field.erb

**Comment by KinGsNowGH** [comment]
Thanks a lot for helping,

I did the changes on:
app/views/evmbaselines/edit.html.erb
app/views/evmbaselines/new.html.erb
app/views/evmbaselines/show.html.erb

but 'app/views/common/_option_field.erb' i couldnt find 'calendar_for(:based_on)':
```
<% content_for :header_tags do %>^M
  <%= stylesheet_link_tag "issue_evm", plugin: "redmine_issue_evm" %>^M
  <%= javascript_include_tag "Chart.bundle.min.js", plugin: "redmine_issue_evm" %>^M
  <%= javascript_include_tag "chartjs-plugin-annotation.min.js", plugin: "redmine_issue_evm" %>^M
<% end %>^M
<script>^M
  function disableobject( object, ischecked ) {^M
    document.getElementById(object).disabled = ischecked;^M
  }^M
</script>^M
<!--option -->^M
<h2><%= l(:title_evm_tab) %></h2>^M
<h3><%= yield :title_sub %></h3>^M
<%= form_tag url_for(action: :index), method: :get, id: "query_form" do %>^M
  <fieldset id="filters" class="collapsible">^M
    <legend onclick="toggleFieldset(this);" class="icon icon-collapsed"><%= l(:label_options) %></legend>^M
    <div style="display: none;">^M
      <!-- basis date -->^M
      <div class="option-col">^M
        <p><%= l(:label_basis_date) %></p>^M
        <%= date_field_tag("basis_date", @cfg_param[:basis_date], size: 8) %><%= calendar_for("basis_date") %>^M
      </div>^M
      <!-- additional option of each page -->^M
      <%= yield :additional_option %>^M
    </div>^M
  </fieldset>^M
  <!-- Apply button -->^M
  <p class="buttons">^M
    <%= link_to "#", {onclick: "$(this).closest('form').submit()", class: "icon icon-checked" } do l(:button_apply) end %>^M
    <%= link_to l(:button_clear), { basis_date: Date.today }, :class => "icon icon-reload"  %>^M
  </p>^M
<% end %>^M
```

I'm still getting an error:
```
Started GET "/projects/project-raizen-monit-radios/evmbaselines/new?id=61" for 127.0.0.1 at 2020-11-19 09:41:31 -0300
Processing by EvmbaselinesController#new as HTML
  Parameters: {"id"=>"61", "project_id"=>"project-raizen-monit-radios"}
  Current user: raphael.franca (id=6)
  Rendered plugins/redmine_issue_evm/app/views/evmbaselines/new.html.erb within layouts/base (14.0ms)
Completed 500 Internal Server Error in 37ms (ActiveRecord: 6.1ms)

ActionView::Template::Error (undefined method `gsub!' for :based_on:Symbol):
     9:     </p>
    10:     <p>
    11:       <%= f.label :based_on, l(:label_based_on) %>
    12:       <%= f.date_field :based_on, size: 8, required: true %><%= calendar_for(@evm_baselines.based_on) %>
    13:     </p>
    14:     <p>
    15:       <%= label :bac, l(:label_baseline_bac) %>
  plugins/redmine_dmsf/lib/redmine_dmsf/patches/application_helper_patch.rb:40:in `calendar_for_with_square_brackets'
  plugins/redmine_issue_evm/app/views/evmbaselines/new.html.erb:12:in `block in _cc5c2590e9abac6c4390004c419b4df6'
  plugins/redmine_issue_evm/app/views/evmbaselines/new.html.erb:4:in `_cc5c2590e9abac6c4390004c419b4df6'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

**Comment by KinGsNowGH** [comment]
> @KinGsNowGH
> Thank you for reporting.
> Perhaps your installation of "redmine_dmsf" is the cause of the error. Its extended functionality does not seem to recognize "basis date of baseline" as a date.
> If possible, could you please try to change it as follows?
> 
> `calendar_for(:based_on) -> calendar_for(@evm_baselines.based_on)`
> 
> at follow files,
> app/views/evmbaselines/edit.html.erb
> app/views/evmbaselines/new.html.erb
> app/views/evmbaselines/show.html.erb
> app/views/common/_option_field.erb

I removed dmsf and i got no more errors, so its true. But its possible to adapt evm to work with dmsf? i'm using an older version of dmsf 'redmine_dmsf 1.6.0' that stil works with Redmine version 3.4.13.stable because of dependecy problems as i saw on dmsf github page.

**Comment by momibun926** [comment]
@KinGsNowGH 
Thank you for try to remove redmine_dmsf.


calendar_for(:based_on) -> calendar_for(@evm_baselines.based_on)

After changed code, you need to restart redemine. did you restart redmine?

**Comment by KinGsNowGH** [comment]
> @KinGsNowGH
> Thank you for try to remove redmine_dmsf.
> 
> calendar_for(:based_on) -> calendar_for(@evm_baselines.based_on)
> 
> After changed code, you need to restart redemine. did you restart redmine?

I didnt, but now i made the changes and i still got error:
```
Started GET "/projects/project-raizen-monit-radios/evmbaselines/new?id=61" for 127.0.0.1 at 2020-11-19 12:07:25 -0300
Processing by EvmbaselinesController#new as HTML
  Parameters: {"id"=>"61", "project_id"=>"project-raizen-monit-radios"}
  Current user: raphael.franca (id=6)
  Rendered plugins/redmine_issue_evm/app/views/evmbaselines/new.html.erb within layouts/base (19.5ms)
Completed 500 Internal Server Error in 87ms (ActiveRecord: 10.0ms)

ActionView::Template::Error (undefined method `gsub!' for Thu, 19 Nov 2020:Date):
     9:     </p>
    10:     <p>
    11:       <%= f.label :based_on, l(:label_based_on) %>
    12:       <%= f.date_field :based_on, size: 8, required: true %><%= calendar_for(@evm_baselines.based_on) %>
    13:     </p>
    14:     <p>
    15:       <%= label :bac, l(:label_baseline_bac) %>
  plugins/redmine_dmsf/lib/redmine_dmsf/patches/application_helper_patch.rb:40:in `calendar_for_with_square_brackets'
  plugins/redmine_issue_evm/app/views/evmbaselines/new.html.erb:12:in `block in _794ef05423bb91c92a50761c5020666c'
  plugins/redmine_issue_evm/app/views/evmbaselines/new.html.erb:4:in `_794ef05423bb91c92a50761c5020666c'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

**Comment by KinGsNowGH** [comment]
As a test, i commented 2 lines from 'plugins/redmine_dmsf/lib/redmine_dmsf/patches/application_helper_patch.rb'.
```
...
        # If the field_id contains square brackets, jQuery is unable to find the tag by it's ID and therefore the Date
        # picker is missing when a DMSF custom filed has got the date format.
        def calendar_for_with_square_brackets(field_id)
          #field_id.gsub! '[', '\\\\\\['
          #field_id.gsub! ']', '\\\\\\]'
          calendar_for_without_square_brackets field_id
        end
...
```
And it worked as intended, i could use baseline creation, but i didnt made any exaustive test to guarantee that dmsf is working as intended.

**Comment by momibun926** [comment]
@KinGsNowGH 
OK, I have a suggestion for you.
redmine_dmfs is using gsub expects a String type. However, calendar_for seems to usually expect a DATE type.
So we think we should change it so that it only works when it's a string type.

```
        # If the field_id contains square brackets, jQuery is unable to find the tag by it's ID and therefore the Date
        # picker is missing when a DMSF custom filed has got the date format.
        def calendar_for_with_square_brackets(field_id)
          field_id.gsub! '[', '\\\\\\['
          field_id.gsub! ']', '\\\\\\]'
          calendar_for_without_square_brackets field_id
        end
```

Fix it as follows,

```
        # If the field_id contains square brackets, jQuery is unable to find the tag by it's ID and therefore the Date
        # picker is missing when a DMSF custom filed has got the date format.
        def calendar_for_with_square_brackets(field_id)
          if field_id.is_a?(String)
            field_id.gsub! '[', '\\\\\\['
            field_id.gsub! ']', '\\\\\\]'
            calendar_for_without_square_brackets field_id
          end
        end
```

**Comment by KinGsNowGH** [comment]
I'm sorry about the delay.
But i got this problem when i did as suggested:

```
2021-01-11T12:45:51.200982741Z NameError: undefined local variable or method `field_id' for RedmineDmsf::Patches::ApplicationHelperPatch::InstanceMethods:Module
2021-01-11T12:45:51.201808172Z /home/redmine/redmine/plugins/redmine_dmsf/lib/redmine_dmsf/patches/application_helper_patch.rb:40:in `<module:InstanceMethods>'
2021-01-11T12:45:51.201835015Z /home/redmine/redmine/plugins/redmine_dmsf/lib/redmine_dmsf/patches/application_helper_patch.rb:35:in `<module:ApplicationHelperPatch>'
2021-01-11T12:45:51.201844420Z /home/redmine/redmine/plugins/redmine_dmsf/lib/redmine_dmsf/patches/application_helper_patch.rb:25:in `<module:Patches>'
2021-01-11T12:45:51.201851488Z /home/redmine/redmine/plugins/redmine_dmsf/lib/redmine_dmsf/patches/application_helper_patch.rb:24:in `<module:RedmineDmsf>'
2021-01-11T12:45:51.201858178Z /home/redmine/redmine/plugins/redmine_dmsf/lib/redmine_dmsf/patches/application_helper_patch.rb:23:in `<top (required)>'
2021-01-11T12:45:51.201864760Z /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
2021-01-11T12:45:51.201871137Z /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
2021-01-11T12:45:51.201877511Z /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `block in require'
2021-01-11T12:45:51.201901277Z /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:240:in `load_dependency'
2021-01-11T12:45:51.201908971Z /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
2021-01-11T12:45:51.201915516Z /home/redmine/redmine/plugins/redmine_dmsf/lib/redmine_dmsf.rb:35:in `<top (required)>'
2021-01-11T12:45:51.201921849Z /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
2021-01-11T12:45:51.201928124Z /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
2021-01-11T12:45:51.201934396Z /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `block in require'
2021-01-11T12:45:51.201940892Z /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:240:in `load_dependency'
2021-01-11T12:45:51.201947298Z /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
2021-01-11T12:45:51.201953786Z /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:360:in `require_or_load'
2021-01-11T12:45:51.201961333Z /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:317:in `depend_on'
2021-01-11T12:45:51.201968359Z /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:233:in `require_dependency'
2021-01-11T12:45:51.201974813Z /home/redmine/redmine/plugins/redmine_dmsf/after_init.rb:2:in `<top (required)>'
2021-01-11T12:45:51.201981205Z /home/redmine/redmine/plugins/redmine_dmsf/init.rb:65:in `require_relative'
2021-01-11T12:45:51.201987356Z /home/redmine/redmine/plugins/redmine_dmsf/init.rb:65:in `<top (required)>'
2021-01-11T12:45:51.201993634Z /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
2021-01-11T12:45:51.201999955Z /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
2021-01-11T12:45:51.202006224Z /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `block in require'
2021-01-11T12:45:51.202012647Z /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:240:in `load_dependency'
2021-01-11T12:45:51.202019107Z /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
2021-01-11T12:45:51.202025563Z /home/redmine/redmine/lib/redmine/plugin.rb:155:in `block in load'
2021-01-11T12:45:51.202031705Z /home/redmine/redmine/lib/redmine/plugin.rb:146:in `each'
2021-01-11T12:45:51.202037830Z /home/redmine/redmine/lib/redmine/plugin.rb:146:in `load'
2021-01-11T12:45:51.202043981Z /home/redmine/redmine/config/initializers/30-redmine.rb:21:in `<top (required)>'
2021-01-11T12:45:51.202056662Z /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:268:in `load'
2021-01-11T12:45:51.202064053Z /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:268:in `block in load'
2021-01-11T12:45:51.202071086Z /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:240:in `load_dependency'
2021-01-11T12:45:51.202077552Z /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:268:in `load'
2021-01-11T12:45:51.202083896Z /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/railties-4.2.11.1/lib/rails/engine.rb:652:in `block in load_config_initializer'
2021-01-11T12:45:51.202090889Z /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.11.1/lib/active_support/notifications.rb:166:in `instrument'
2021-01-11T12:45:51.202097878Z /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/railties-4.2.11.1/lib/rails/engine.rb:651:in `load_config_initializer'
2021-01-11T12:45:51.202104378Z /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/railties-4.2.11.1/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
2021-01-11T12:45:51.202110972Z /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/railties-4.2.11.1/lib/rails/engine.rb:615:in `each'
2021-01-11T12:45:51.202117230Z /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/railties-4.2.11.1/lib/rails/engine.rb:615:in `block in <class:Engine>'
2021-01-11T12:45:51.202123619Z /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/railties-4.2.11.1/lib/rails/initializable.rb:30:in `instance_exec'
2021-01-11T12:45:51.202129887Z /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/railties-4.2.11.1/lib/rails/initializable.rb:30:in `run'
2021-01-11T12:45:51.202136125Z /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/railties-4.2.11.1/lib/rails/initializable.rb:55:in `block in run_initializers'
2021-01-11T12:45:51.202142440Z /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/railties-4.2.11.1/lib/rails/initializable.rb:44:in `each'
2021-01-11T12:45:51.202148713Z /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/railties-4.2.11.1/lib/rails/initializable.rb:44:in `tsort_each_child'
2021-01-11T12:45:51.202154962Z /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/railties-4.2.11.1/lib/rails/initializable.rb:54:in `run_initializers'
2021-01-11T12:45:51.202161236Z /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/railties-4.2.11.1/lib/rails/application.rb:352:in `initialize!'
2021-01-11T12:45:51.202167460Z /home/redmine/redmine/config/environment.rb:14:in `<top (required)>'
2021-01-11T12:45:51.202173635Z /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
2021-01-11T12:45:51.202179817Z /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
2021-01-11T12:45:51.202186026Z /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `block in require'
2021-01-11T12:45:51.202198090Z /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:240:in `load_dependency'
2021-01-11T12:45:51.202206218Z /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
2021-01-11T12:45:51.202212975Z /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/railties-4.2.11.1/lib/rails/application.rb:328:in `require_environment!'
2021-01-11T12:45:51.202219273Z /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/railties-4.2.11.1/lib/rails/application.rb:457:in `block in run_tasks_blocks'
2021-01-11T12:45:51.202225649Z /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
2021-01-11T12:45:51.203765338Z Tasks: TOP => redmine:plugins:migrate => environment
2021-01-11T12:45:51.203785491Z (See full trace by running task with --trace)
```
