### ISSUE TITLE
Does it work with Redmine 2.4.2.stable?

### ISSUE THREAD

**Issue by MarioVillani** [momibun926/redmine_issue_evm#49]
I installed it on Redmine 2.4.2, it launches those errors:

```
Started GET "/myproject/projects/myproject/evms" for 193.205.162.64 at 2015-12-14 09:15:29 +0000

ActionController::RoutingError (undefined method `before_action' for EvmsController:Class):
  plugins/redmine_issue_evm/app/controllers/evms_controller.rb:7:in `<class:EvmsController>'
  plugins/redmine_issue_evm/app/controllers/evms_controller.rb:3:in `<top (required)>'
  /usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:251:in `require'
  /usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:251:in `block in require'
  /usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:236:in `load_dependency'
  /usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:251:in `require'
  /usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:359:in `require_or_load'
  /usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:502:in `load_missing_constant'
  /usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:192:in `block in const_missing'
  /usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:190:in `each'
  /usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:190:in `const_missing'
  /usr/lib/ruby/vendor_ruby/active_support/inflector/methods.rb:230:in `block in constantize'
  /usr/lib/ruby/vendor_ruby/active_support/inflector/methods.rb:229:in `each'
  /usr/lib/ruby/vendor_ruby/active_support/inflector/methods.rb:229:in `constantize'
  /usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:554:in `get'
  /usr/lib/ruby/vendor_ruby/action_dispatch/routing/route_set.rb:69:in `controller_reference'
  /usr/lib/ruby/vendor_ruby/action_dispatch/routing/route_set.rb:54:in `controller'
  /usr/lib/ruby/vendor_ruby/action_dispatch/routing/route_set.rb:32:in `call'
  /usr/lib/ruby/vendor_ruby/journey/router.rb:68:in `block in call'
  /usr/lib/ruby/vendor_ruby/journey/router.rb:56:in `each'
  /usr/lib/ruby/vendor_ruby/journey/router.rb:56:in `call'
  /usr/lib/ruby/vendor_ruby/action_dispatch/routing/route_set.rb:608:in `call'
  /usr/lib/ruby/vendor_ruby/rack/openid.rb:98:in `call'
  /usr/lib/ruby/vendor_ruby/action_dispatch/middleware/best_standards_support.rb:17:in `call'
  /usr/lib/ruby/vendor_ruby/rack/etag.rb:23:in `call'
  /usr/lib/ruby/vendor_ruby/rack/conditionalget.rb:25:in `call'
  /usr/lib/ruby/vendor_ruby/action_dispatch/middleware/head.rb:14:in `call'
  /usr/lib/ruby/vendor_ruby/action_dispatch/middleware/params_parser.rb:21:in `call'
  /usr/lib/ruby/vendor_ruby/action_dispatch/middleware/flash.rb:242:in `call'
  /usr/lib/ruby/vendor_ruby/rack/session/abstract/id.rb:210:in `context'
  /usr/lib/ruby/vendor_ruby/rack/session/abstract/id.rb:205:in `call'
  /usr/lib/ruby/vendor_ruby/action_dispatch/middleware/cookies.rb:341:in `call'
  /usr/lib/ruby/vendor_ruby/active_record/query_cache.rb:64:in `call'
  /usr/lib/ruby/vendor_ruby/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
  /usr/lib/ruby/vendor_ruby/action_dispatch/middleware/callbacks.rb:28:in `block in call'
  /usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:405:in `_run__3249842283438076298__call__1292781571854966464__callbacks'
  /usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:405:in `__run_callback'
  /usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:385:in `_run_call_callbacks'
  /usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:81:in `run_callbacks'
  /usr/lib/ruby/vendor_ruby/action_dispatch/middleware/callbacks.rb:27:in `call'
  /usr/lib/ruby/vendor_ruby/action_dispatch/middleware/remote_ip.rb:31:in `call'
  /usr/lib/ruby/vendor_ruby/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
  /usr/lib/ruby/vendor_ruby/action_dispatch/middleware/show_exceptions.rb:56:in `call'
  /usr/lib/ruby/vendor_ruby/rails/rack/logger.rb:32:in `call_app'
  /usr/lib/ruby/vendor_ruby/rails/rack/logger.rb:16:in `block in call'
  /usr/lib/ruby/vendor_ruby/active_support/tagged_logging.rb:22:in `tagged'
  /usr/lib/ruby/vendor_ruby/rails/rack/logger.rb:16:in `call'
  /usr/lib/ruby/vendor_ruby/action_dispatch/middleware/request_id.rb:22:in `call'
  /usr/lib/ruby/vendor_ruby/rack/methodoverride.rb:21:in `call'
  /usr/lib/ruby/vendor_ruby/rack/runtime.rb:17:in `call'
  /usr/lib/ruby/vendor_ruby/active_support/cache/strategy/local_cache.rb:72:in `call'
  /usr/lib/ruby/vendor_ruby/rack/lock.rb:15:in `call'
  /usr/lib/ruby/vendor_ruby/action_dispatch/middleware/static.rb:63:in `call'
  /usr/lib/ruby/vendor_ruby/rack/cache/context.rb:136:in `forward'
  /usr/lib/ruby/vendor_ruby/rack/cache/context.rb:245:in `fetch'
  /usr/lib/ruby/vendor_ruby/rack/cache/context.rb:185:in `lookup'
  /usr/lib/ruby/vendor_ruby/rack/cache/context.rb:66:in `call!'
  /usr/lib/ruby/vendor_ruby/rack/cache/context.rb:51:in `call'
  /usr/lib/ruby/vendor_ruby/rails/engine.rb:484:in `call'
  /usr/lib/ruby/vendor_ruby/rails/application.rb:231:in `call'
  /usr/lib/ruby/vendor_ruby/rails/railtie/configurable.rb:30:in `method_missing'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:77:in `process_request'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:142:in `accept_and_process_next_request'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:448:in `block (3 levels) in start_threads'

Completed 500 Internal Server Error in 12.7ms

ActionView::Template::Error (undefined method `id' for nil:NilClass):
    12: <% end %>
    13: <!-- Basline setting -->
    14: <div class="contextual">
    15:   <%= link_to l(:label_baseline_set), {controller:"evmbaselines", action:"index", id: @project.id} ,:class => 'icon icon-edit'%>
    16: </div>
    17: <!--Header-->
    18: <h2><%= l(:title_evm_tab)%></h2>
  plugins/redmine_issue_evm/app/views/evms/index.html.erb:15:in `_plugins_redmine_issue_evm_app_views_evms_index_html_erb___214220133827280966_35794160'
  /usr/lib/ruby/vendor_ruby/action_view/template.rb:145:in `block in render'
  /usr/lib/ruby/vendor_ruby/active_support/notifications.rb:125:in `instrument'
  /usr/lib/ruby/vendor_ruby/action_view/template.rb:143:in `render'
  /usr/lib/ruby/vendor_ruby/action_view/renderer/template_renderer.rb:47:in `block (2 levels) in render_template'
  /usr/lib/ruby/vendor_ruby/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
  /usr/lib/ruby/vendor_ruby/active_support/notifications.rb:123:in `block in instrument'
  /usr/lib/ruby/vendor_ruby/active_support/notifications/instrumenter.rb:20:in `instrument'
  /usr/lib/ruby/vendor_ruby/active_support/notifications.rb:123:in `instrument'
  /usr/lib/ruby/vendor_ruby/action_view/renderer/abstract_renderer.rb:38:in `instrument'
  /usr/lib/ruby/vendor_ruby/action_view/renderer/template_renderer.rb:46:in `block in render_template'
  /usr/lib/ruby/vendor_ruby/action_view/renderer/template_renderer.rb:54:in `render_with_layout'
  /usr/lib/ruby/vendor_ruby/action_view/renderer/template_renderer.rb:45:in `render_template'
  /usr/lib/ruby/vendor_ruby/action_view/renderer/template_renderer.rb:18:in `render'
  /usr/lib/ruby/vendor_ruby/action_view/renderer/renderer.rb:36:in `render_template'
  /usr/lib/ruby/vendor_ruby/action_view/renderer/renderer.rb:17:in `render'
  /usr/lib/ruby/vendor_ruby/abstract_controller/rendering.rb:110:in `_render_template'
  /usr/lib/ruby/vendor_ruby/action_controller/metal/streaming.rb:225:in `_render_template'
  /usr/lib/ruby/vendor_ruby/abstract_controller/rendering.rb:103:in `render_to_body'
  /usr/lib/ruby/vendor_ruby/action_controller/metal/renderers.rb:28:in `render_to_body'
  /usr/lib/ruby/vendor_ruby/action_controller/metal/compatibility.rb:50:in `render_to_body'
 /usr/lib/ruby/vendor_ruby/abstract_controller/rendering.rb:88:in `render'
  /usr/lib/ruby/vendor_ruby/action_controller/metal/rendering.rb:16:in `render'
  /usr/lib/ruby/vendor_ruby/action_controller/metal/instrumentation.rb:40:in `block (2 levels) in render'
  /usr/lib/ruby/vendor_ruby/active_support/core_ext/benchmark.rb:5:in `block in ms'
  /usr/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
  /usr/lib/ruby/vendor_ruby/active_support/core_ext/benchmark.rb:5:in `ms'
  /usr/lib/ruby/vendor_ruby/action_controller/metal/instrumentation.rb:40:in `block in render'
  /usr/lib/ruby/vendor_ruby/action_controller/metal/instrumentation.rb:83:in `cleanup_view_runtime'
  /usr/lib/ruby/vendor_ruby/active_record/railties/controller_runtime.rb:24:in `cleanup_view_runtime'
  /usr/lib/ruby/vendor_ruby/action_controller/metal/instrumentation.rb:39:in `render'
  /usr/lib/ruby/vendor_ruby/action_controller/metal/implicit_render.rb:10:in `default_render'
  /usr/lib/ruby/vendor_ruby/action_controller/metal/implicit_render.rb:4:in `send_action'
  /usr/lib/ruby/vendor_ruby/abstract_controller/base.rb:167:in `process_action'
  /usr/lib/ruby/vendor_ruby/action_controller/metal/rendering.rb:10:in `process_action'
  /usr/lib/ruby/vendor_ruby/abstract_controller/callbacks.rb:18:in `block in process_action'
  /usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:469:in `_run__3694420442007710827__process_action__2481296603734003186__callbacks'
  /usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:405:in `__run_callback'
  /usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
  /usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:81:in `run_callbacks'
  /usr/lib/ruby/vendor_ruby/abstract_controller/callbacks.rb:17:in `process_action'
  /usr/lib/ruby/vendor_ruby/action_controller/metal/rescue.rb:29:in `process_action'
  /usr/lib/ruby/vendor_ruby/action_controller/metal/instrumentation.rb:30:in `block in process_action'
  /usr/lib/ruby/vendor_ruby/active_support/notifications.rb:123:in `block in instrument'
  /usr/lib/ruby/vendor_ruby/active_support/notifications/instrumenter.rb:20:in `instrument'
  /usr/lib/ruby/vendor_ruby/active_support/notifications.rb:123:in `instrument'
  ...
```

**Comment by momibun926** [comment]
@MarioVillani
Sorry,required 3.1 above.
